export enum ErrorCode {
  DUPLICATED_OPERATION = 'DUPLICATED_OPERATION', // 重复操作
  FREQUENT_OPERATION = 'FREQUENT_OPERATION', // 频繁操作
  OPERATION_FAILED = 'OPERATION_FAILED', // 操作失败
  MISSING_WALLET_ADDRESS = 'MISSING_WALLET_ADDRESS', // 缺少钱包地址
  INVALID_SIGNATURE = 'INVALID_SIGNATURE', // 无效签名
  SERVER_ERROR = 'SERVER_ERROR', // 服务器错误
  INVALID_TRANSACTION = 'INVALID_TRANSACTION', // 无效交易
  TRANSACTION_FAILED = 'TRANSACTION_FAILED', // 交易失败
  INVALID_AMOUNT = 'INVALID_AMOUNT', // 无效金额
  NOT_FOUND = 'NOT_FOUND', // 未找到
  INSUFFICIENT_REWARD_CAP = 'INSUFFICIENT_REWARD_CAP' // 奖励上限不足
}